name: automerge

on:
  pull_request:
    types:
      - synchronize
      - edited
      - ready_for_review
      - reopened
      - unlocked
  check_suite:
    types:
      - completed
  workflow_dispatch: {}

jobs:
  automerge:
    uses: mih-kopylov/workflows/.github/workflows/automerge.yml@automerge
    secrets:
      token: ${{ secrets.UPDATE_DEPENDENCIES_PAT }}
