name: release
on:
  workflow_dispatch: {}
  push:
    tags:
      - '*'

jobs:
  create-release:
    uses: mih-kopylov/workflows/.github/workflows/release.yml@master
    with:
      docker: false

  build-wiki:
    needs: create-release
    uses: mih-kopylov/workflows/.github/workflows/build-wiki.yml@master
    with:
      app: ./app/docs
