name: release
on:
  workflow_dispatch: {}
  push:
    tags:
      - '*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure golang
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - name: Create a release
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
