name: update-dependencies
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}

jobs:
  update-dependencies:
    uses: mih-kopylov/workflows/.github/workflows/update-dependencies.yml@automerge
    secrets:
      token: ${{ secrets.UPDATE_DEPENDENCIES_PAT }}
